# Generated by Django 4.1 on 2022-08-18 20:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='URL')),
                ('short_description', models.TextField(max_length=300, verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата обновления')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Причина обновления')),
                ('is_fixed', models.BooleanField(db_index=True, default=False, verbose_name='Зафиксировано')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Превью поста')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='article_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор материала')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Автор обновления')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'app_articles',
                'ordering': ('-is_fixed', '-created_at'),
            },
        ),
    ]
