# Generated by Django 4.1 on 2022-09-18 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_alter_article_full_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время добавления оценки')),
                ('value', models.SmallIntegerField(choices=[(1, 'Нравится'), (-1, 'Не нравится')], verbose_name='Оценка')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Адрес')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_rating', to='blog.article', verbose_name='Статья')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_rating_author', to=settings.AUTH_USER_MODEL, verbose_name='Оценил')),
            ],
            options={
                'verbose_name': 'Рейтинг материала',
                'verbose_name_plural': 'Рейтинг материалов',
                'db_table': 'app_ratings',
                'ordering': ('-created_at',),
            },
        ),
    ]
